.TH SuperGoose 3.0 "Eric Morales, Victor Yrazusta, Alejandro Pascual y Javier Lougedo" "version 3.0" "COMMAND GUIDE"
." This is our manual page. It will be used to give the player a description for our game and all its utilities, walkthrough and else.
." Created by Javier Lougedo

.SH COMMANDS
.P
.SS PROMODE (P)
ProMode is used when you are going to move repeatedly. It allows you to move inmediately without needing to press enter. To activate it, just press P and enter. You will now be in ProMode. Use WASD to move in any direction you want to, as Q or E to move above or below. To deactivate it, just press P again.
.P
.SS MOVEMENT (M)
In normal mode, you will be able to move in any direction (if allowed) by pressing "move" or "m" followed by any cardinal direction or up and down, or you can press WASD and Q and E to move in any direction without the need of "m" or "move".
.P
.SS GRASP (G)
This command is used to grasp objects from the floor and put them in your inventory. It will only work with nearby, visible and moveable objects.
.P
	To use it, type "grasp" or "g", followed by an objects name or identificator.
.P
.SS DROP (L)
This command is used to drop objects from the inventory to the floor. Carefull, cause it works with dark rooms.
.P
	To use it, type "drop" or "d", followed by an objects name or identificator.
.P
.SS Throw (t)
.P
	To use it, type "throw" or "t", followed by an objects name or identificator.
.P
.SS CHECK (C)
This command will check the space if no object is added after it or the given object.
.P
	To use it, type "check" or "c", followed by an objects name or identificator. Followed by "space" or "s" checks current space.
.P
.SS OPEN (O)
Used to open closed paths, like doors or blowable walls.
.P
	To use it, type "open <path> with <key-object>". Carefull, sometimes this will mean loosing the object!
.P
.SS TURN ON - TURN OFF (TON-TOFF)
Turn on works to light up or down rooms. You will only be able to use it with gloweable objects or sometimes with buttons.
.P
	To use it, type "turnon <gloweable-object>" or "turnoff...".
.P
.SS SAVE (SV)
This command will save your game and store on the save_games folder.
.P
	To use it, type "save" or "sv", followed by the name you want to give the file. (Default: "autosave.game").
.P
.SS LOAD (LD)
This command will load a game from the save_games folder.
.P
	To use it, type "load" or "ld", and then choose the file you will want to load.
.P
.SS HELP (H)
This command will open this command guide for you.
.P
	To use it, type "help" or "h", and the guide will be opened.
.P
