.TH SuperGoose 6 "Eric Morales, Victor Yrazusta, Alejandro Pascual y Javier Lougedo" "version 3.0" "Proyecto de Programacion"
." This is our manual page. It will be used to give the player a description for our game and all its utilities, walkthrough and else.
." Created by Javier Lougedo


.SH NAME
.R SuperGoose. A game to be remembered.

.SH DESCRIPTION
.R SuperGoose is a game created by Javier Lougedo, Eric Morales, Victor Yrazusta and Alejandro Pascual for the programming project assignement on their first engeneering graduate year. Created with passion, hard work and of course, humor, SuperGoose is a game easy and fun to play, with a cool Graphic Engine that will make you love the game, based on Unicode.
.P
.R This game will tell you the story of Hugo, the goose that saved the Geese Kingdom and the Geese Princess from the DUCKALYPSE. Will you be able to survive the adventure as Hugo did? Come and see it, because the ducks wont go easy with you, mate!
.SH

.SH COMMANDS
.P
.SS ProMode (P)
ProMode is used when you are going to move repeatedly. It allows you to move inmediately without needing to press enter. To activate it, just press P and enter. You will now be in ProMode. Use WASD to move in any direction you want to, as Q or E to move above or below. To deactivate it, just press P again.
.P
.SS Movement (M)
In normal mode, you will be able to move in any direction (if allowed) by pressing "move" or "m" followed by any cardinal direction or up and down, or you can press WASD and Q and E to move in any direction without the need of "m" or "move".
.P
.SS GRASP (G)
This command is used to grasp objects from the floor and put them in your inventory. It will only work with nearby, visible and moveable objects.
.P
	To use it, type "grasp" or "g", followed by an objects name or identificator.
.P
.SS LEAVE (L)
This command is used to drop objects from the inventory to the floor. Carefull, cause it works with dark rooms.
.P
	To use it, type "drop" or "d", followed by an objects name or identificator.
.P
.SS CHECK (C)
This command will check the space if no object is added after it or the given object.
.P
	To use it, type "check" or "c", followed by an objects name or identificator. Leave empty to check space.
.P
.SS OPEN (O)
Used to open closed paths, like doors or blowable walls.
.P
	To use it, type "open <path> with <key-object>". Carefull, sometimes this will mean loosing the object!
.P

.SS TURN ON - TURN OFF (TON-TOFF)
Turn on works to light up or down rooms. You will only be able to use it with gloweable objects or sometimes with buttons.
.P
	To use it, type "turnon <gloweable-object>" or "turnoff...".
.P
.SS SAVE (SV)
This command will save your game and store on the save_games folder.
.P
	To use it, type "save" or "sv", followed by the name you want to give the file. (Default: "autosave.game").
.P
.SS LOAD (LD)
This command will load a game from the save_games folder.
.P
	To use it, type "load" or "ld", and then choose the file you will want to load.
.P
.SS HELP (H)
This command will open this command guide for you.
.P
	To use it, type "help" or "h", and the guide will be opened.
.P

.SH FILES
.SS ./datafiles
.P
This are the datafiles for our tests and else. This is private, so please don't touch!
.RE
.SS ./include
.P
This is the folder to store the header files. This is private, so don't touch anything.
.RE
.SS ./lib
.P
This folder includes important files for our game, as the guide, the controls and the terms of use. This is only for read during gameplay! And it is private, so please don't touch!
.RE
.SS ./logfiles
.P
This is the folder to store logfiles. One of them will have the walkthrough and the others are to test if the game works properly. This is private, so please don't touch!
.RE
.SS ./MEETINGS
.P
This is to store the meetings we are doing through the project. This is private, so please don't touch!
.RE
.SS ./obj
.P
This folder stores the object files in order to make the game and tests. This is private, so please don't touch!
.RE
.SS ./save_games
.P
This folder stores the saved games. It has an example game with a non-started adventure.
.RE
.SS ./src
.P
This folder stores the source code of SuperGoose. Very private and delicate, respect it :).
.RE
.SS ./testfiles
.P
This is to store all the test files our game needs to be checked.
.RE
.SS ./testfiles
.P
This is to store all the test files our game needs to be checked.
.RE
.SS ./Doxyfile
.P
The doxyfile, used to make the coding documentation.
.RE
.SS ./Makefile
.P
Our makefile, the one who rules all the action.
.RE
.SS ./SuperGoose
.P
The actual game. Have fun!
.RE

.SH OPTION
.BI -l " logfile"
.P
	Specifies the file you want to generate with the input commands you give. This option is optional.
.P
.BI -h
.P
	Hardcore mode. Only for the brave.
