/**
 * @brief It defines the different graphic descriptions in unicode
 * @file graphic_descriptions.h
 * @author Alejandro Pascual
 * @version 1.0
 * @date 06-05-2018
 * @copyright GNU Public License
 */

#ifndef GRAPHIC_DESCRIPTIONS_H
#define GRAPHIC_DESCRIPTIONS_H

#define STD_ROOM_0 L"┏━━━━━━━━━━━━━━━━━━┓"
#define STD_ROOM_1 L"┃                  ┃"
#define STD_ROOM_2 L"┃                  ┃"
#define STD_ROOM_3 L"┃                  ┃"
#define STD_ROOM_4 L"┃                  ┃"
#define STD_ROOM_5 L"┃                  ┃"
#define STD_ROOM_6 L"┃                  ┃"
#define STD_ROOM_7 L"┃                  ┃"
#define STD_ROOM_8 L"┃                  ┃"
#define STD_ROOM_9 L"┗━━━━━━━━━━━━━━━━━━┛"

#define HALLWAY_1_0 L"┏━━━━━┓ •  • ┏━━━━━┓"
#define HALLWAY_1_1 L"┃     ┃      ┃     ┃"
#define HALLWAY_1_2 L"┃     ┃      ┃     ┃"
#define HALLWAY_1_3 L"┃     ┃      ┗━━━━━┛"
#define HALLWAY_1_4 L"┃     ┃            •"
#define HALLWAY_1_5 L"┃     ┃            •"
#define HALLWAY_1_6 L"┃     ┃      ┏━━━━━┓"
#define HALLWAY_1_7 L"┃     ┃      ┃     ┃"
#define HALLWAY_1_8 L"┃     ┃      ┃     ┃"
#define HALLWAY_1_9 L"┗━━━━━┛ •  • ┗━━━━━┛"

#define HALLWAY_2_0 L"┏━━━━━┓ •  • ┏━━━━━┓"
#define HALLWAY_2_1 L"┃     ┃      ┃     ┃"
#define HALLWAY_2_2 L"┃     ┃      ┃     ┃"
#define HALLWAY_2_3 L"┗━━━━━┛      ┗━━━━━┛"
#define HALLWAY_2_4 L"•                  •"
#define HALLWAY_2_5 L"•                  •"
#define HALLWAY_2_6 L"┏━━━━━┓      ┏━━━━━┓"
#define HALLWAY_2_7 L"┃     ┃      ┃     ┃"
#define HALLWAY_2_8 L"┃     ┃      ┃     ┃"
#define HALLWAY_2_9 L"┗━━━━━┛ •  • ┗━━━━━┛"

#define HALLWAY_3_0 L"┏━━━━━━━━━━━━━━━━━━┓"
#define HALLWAY_3_1 L"┃                  ┃"
#define HALLWAY_3_2 L"┃                  ┃"
#define HALLWAY_3_3 L"┗━━━━━━━━━━━━━━━━━━┛"
#define HALLWAY_3_4 L"•                  •"
#define HALLWAY_3_5 L"•                  •"
#define HALLWAY_3_6 L"┏━━━━━━━━━━━━━━━━━━┓"
#define HALLWAY_3_7 L"┃                  ┃"
#define HALLWAY_3_8 L"┃                  ┃"
#define HALLWAY_3_9 L"┗━━━━━━━━━━━━━━━━━━┛"

#define HALLWAY_4_0 L"┏━━━━━━━━━━━━━━━━━━┓"
#define HALLWAY_4_1 L"┃                  ┃"
#define HALLWAY_4_2 L"┃                  ┃"
#define HALLWAY_4_3 L"┗━━━━━━━━━━━━━━━━━━┛"
#define HALLWAY_4_4 L"•                  •"
#define HALLWAY_4_5 L"•                  •"
#define HALLWAY_4_6 L"┏━━━━━┓      ┏━━━━━┓"
#define HALLWAY_4_7 L"┃     ┃      ┃     ┃"
#define HALLWAY_4_8 L"┃     ┃      ┃     ┃"
#define HALLWAY_4_9 L"┗━━━━━┛ •  • ┗━━━━━┛"

#define HALLWAY_5_0 L"┏━━━━━┓ •  • ┏━━━━━┓"
#define HALLWAY_5_1 L"┃     ┃      ┃     ┃"
#define HALLWAY_5_2 L"┃     ┃      ┃     ┃"
#define HALLWAY_5_3 L"┗━━━━━┛      ┃     ┃"
#define HALLWAY_5_4 L"•            ┃     ┃"
#define HALLWAY_5_5 L"•            ┃     ┃"
#define HALLWAY_5_6 L"┏━━━━━┓      ┃     ┃"
#define HALLWAY_5_7 L"┃     ┃      ┃     ┃"
#define HALLWAY_5_8 L"┃     ┃      ┃     ┃"
#define HALLWAY_5_9 L"┗━━━━━┛ •  • ┗━━━━━┛"

#define HALLWAY_6_0 L"┏━━━━━┓ •  • ┏━━━━━┓"
#define HALLWAY_6_1 L"┃     ┃      ┃     ┃"
#define HALLWAY_6_2 L"┃     ┃      ┃     ┃"
#define HALLWAY_6_3 L"┃     ┃      ┗━━━━━┛"
#define HALLWAY_6_4 L"┃     ┃            •"
#define HALLWAY_6_5 L"┃     ┃            •"
#define HALLWAY_6_6 L"┃     ┗━━━━━━━━━━━━┓"
#define HALLWAY_6_7 L"┃                  ┃"
#define HALLWAY_6_8 L"┃                  ┃"
#define HALLWAY_6_9 L"┗━━━━━━━━━━━━━━━━━━┛"

#define HALLWAY_7_0 L"┏━━━━━━━━━━━━━━━━━━┓"
#define HALLWAY_7_1 L"┃                  ┃"
#define HALLWAY_7_2 L"┃                  ┃"
#define HALLWAY_7_3 L"┃     ┏━━━━━━━━━━━━┛"
#define HALLWAY_7_4 L"┃     ┃            •"
#define HALLWAY_7_5 L"┃     ┃            •"
#define HALLWAY_7_6 L"┃     ┃      ┏━━━━━┓"
#define HALLWAY_7_7 L"┃     ┃      ┃     ┃"
#define HALLWAY_7_8 L"┃     ┃      ┃     ┃"
#define HALLWAY_7_9 L"┗━━━━━┛ •  • ┗━━━━━┛"

#define HIBERNATION_ROOM_0 L"┏━━━━━━━━━━━━━━━━━━┓"
#define HIBERNATION_ROOM_1 L"┃ ┏━━━━━━━━━━━━━━┓ ┃"
#define HIBERNATION_ROOM_2 L"┃ ┃ ┏━━━┓  ┏━━━┓ ┃ ┃"
#define HIBERNATION_ROOM_3 L"┃ ┃ ┗━━━┛  ┗━━━┛ ┗━┛"
#define HIBERNATION_ROOM_4 L"┃ ┃                •"
#define HIBERNATION_ROOM_5 L"┃ ┃                •"
#define HIBERNATION_ROOM_6 L"┃ ┃ ┏━━━┓  ┏━━━┓ ┏━┓"
#define HIBERNATION_ROOM_7 L"┃ ┃ ┗━━━┛  ┗━━━┛ ┃ ┃"
#define HIBERNATION_ROOM_8 L"┃ ┗━━━━━━━━━━━━━━┛ ┃"
#define HIBERNATION_ROOM_9 L"┗━━━━━━━━━━━━━━━━━━┛"

#define STAIRS_ROOM_DOWN_0 L"┏━━━━━━━━━━━━━━━━━━┓"
#define STAIRS_ROOM_DOWN_1 L"┃ ┏━━━━━━━━━━┳━━━┓ ┃"
#define STAIRS_ROOM_DOWN_2 L"┃ ┃          ┃   ┃ ┃"
#define STAIRS_ROOM_DOWN_3 L"┗━┛          ┣━━━┫ ┃"
#define STAIRS_ROOM_DOWN_4 L"•            ┣━━━┫ ┃"
#define STAIRS_ROOM_DOWN_5 L"•            ┣━━━┫ ┃"
#define STAIRS_ROOM_DOWN_6 L"┏━┓    ┏━┳━┳━╋━━━┫ ┃"
#define STAIRS_ROOM_DOWN_7 L"┃ ┃    ┃ ┃ ┃ ┃   ┃ ┃"
#define STAIRS_ROOM_DOWN_8 L"┃ ┗━━━━┻━┻━┻━┻━━━┛ ┃"
#define STAIRS_ROOM_DOWN_9 L"┗━━━━━━━━━━━━━━━━━━┛"

#define ELEVATOR_HALL_0 L"┏━━━━━┓ •  • ┏━━━━━┓"
#define ELEVATOR_HALL_1 L"┃     ┃      ┃     ┃"
#define ELEVATOR_HALL_2 L"┃     ┃      ┃     ┃"
#define ELEVATOR_HALL_3 L"┃ ┏━━━┛      ┗━━━┓ ┃"
#define ELEVATOR_HALL_4 L"┃ ┃              ┃ ┃"
#define ELEVATOR_HALL_5 L"┃ ┃              ┃ ┃"
#define ELEVATOR_HALL_6 L"┃ ┃              ┃ ┃"
#define ELEVATOR_HALL_7 L"┃ ┃ ┏━┓      ┏━┓ ┃ ┃"
#define ELEVATOR_HALL_8 L"┃ ┗━┛ ┃      ┃ ┗━┛ ┃"
#define ELEVATOR_HALL_9 L"┗━━━━━┛ •  • ┗━━━━━┛"

#define ELEVATOR_11_0 L"  ┏━━━━ •  • ━━━━┓  "
#define ELEVATOR_11_1 L"  ┃              ┃  "
#define ELEVATOR_11_2 L"  ┃              ┃  "
#define ELEVATOR_11_3 L"  ┃              ┃  "
#define ELEVATOR_11_4 L"  ┃              ┃  "
#define ELEVATOR_11_5 L"  ┃              ┃  "
#define ELEVATOR_11_6 L"  ┃              ┃  "
#define ELEVATOR_11_7 L"  ┃  ↓           ┃  "
#define ELEVATOR_11_8 L"  ┃              ┃  "
#define ELEVATOR_11_9 L"  ┗━━━━━━━━━━━━━━┛  "

#define ELEVATOR_12_0 L"  ┏━━━━ •  • ━━━━┓  "
#define ELEVATOR_12_1 L"  ┃              ┃  "
#define ELEVATOR_12_2 L"  ┃              ┃  "
#define ELEVATOR_12_3 L"  ┃              ┃  "
#define ELEVATOR_12_4 L"  ┃              ┃  "
#define ELEVATOR_12_5 L"  ┃              ┃  "
#define ELEVATOR_12_6 L"  ┃              ┃  "
#define ELEVATOR_12_7 L"  ┃  ↑           ┃  "
#define ELEVATOR_12_8 L"  ┃              ┃  "
#define ELEVATOR_12_9 L"  ┗━━━━━━━━━━━━━━┛  "

#define ELEVATOR_21_0 L"                    "
#define ELEVATOR_21_1 L"┏━━━━━━━━━━━━━━━━━━┓"
#define ELEVATOR_21_2 L"┃                  ┃"
#define ELEVATOR_21_3 L"┃  ↓               ┃"
#define ELEVATOR_21_4 L"┃                  •"
#define ELEVATOR_21_5 L"┃                  •"
#define ELEVATOR_21_6 L"┃                  ┃"
#define ELEVATOR_21_7 L"┃                  ┃"
#define ELEVATOR_21_8 L"┗━━━━━━━━━━━━━━━━━━┛"
#define ELEVATOR_21_9 L"                    "

#define ELEVATOR_22_0 L"                    "
#define ELEVATOR_22_1 L"┏━━━━━━━━━━━━━━━━━━┓"
#define ELEVATOR_22_2 L"┃                  ┃"
#define ELEVATOR_22_3 L"┃  ↑               ┃"
#define ELEVATOR_22_4 L"┃                  •"
#define ELEVATOR_22_5 L"┃                  •"
#define ELEVATOR_22_6 L"┃                  ┃"
#define ELEVATOR_22_7 L"┃                  ┃"
#define ELEVATOR_22_8 L"┗━━━━━━━━━━━━━━━━━━┛"
#define ELEVATOR_22_9 L"                    "

#define WAREHOUSE_0 L"┏━━━━━━━┓ •  • ┏━━━┓"
#define WAREHOUSE_1 L"┃ ┏━━━━━┛      ┗━┓ ┃"
#define WAREHOUSE_2 L"┃ ┃        ┏━━━┓ ┃ ┃"
#define WAREHOUSE_3 L"┗━┛        ┗━━━┛ ┃ ┃"
#define WAREHOUSE_4 L"•    ┏━━━━━━━━━┓ ┃ ┃"
#define WAREHOUSE_5 L"•    ┗━━━━━━━━━┛ ┃ ┃"
#define WAREHOUSE_6 L"┏━┓  ┏━━━┓ ┏━━━┓ ┃ ┃"
#define WAREHOUSE_7 L"┃ ┃  ┗━━━┛ ┗━━━┛ ┃ ┃"
#define WAREHOUSE_8 L"┃ ┗━━━━━━━━━━━━━━┛ ┃"
#define WAREHOUSE_9 L"┗━━━━━━━━━━━━━━━━━━┛"

#define LARGE_WAREHOUSE_0 L"┏━━━━━━━━━━━━━━━━━━┓"
#define LARGE_WAREHOUSE_1 L"┃ ┏━━━━━━━━━━━━━━┓ ┃"
#define LARGE_WAREHOUSE_2 L"┃ ┃┏━━━━━┓┏━━━━━┓┃ ┃"
#define LARGE_WAREHOUSE_3 L"┃ ┃┗━━━━━┛┗━━━━━┛┃ ┃"
#define LARGE_WAREHOUSE_4 L"┃ ┃┏━━━━━━━━━━━┓ ┃ ┃"
#define LARGE_WAREHOUSE_5 L"┃ ┃┗━━━━━━━━━━━┛ ┃ ┃"
#define LARGE_WAREHOUSE_6 L"┃ ┃┏━━━━┓ ┏━━━━┓ ┃ ┃"
#define LARGE_WAREHOUSE_7 L"┃ ┃┗━━━━┛ ┗━━━━┛ ┃ ┃"
#define LARGE_WAREHOUSE_8 L"┃ ┗━━━┓      ┏━━━┛ ┃"
#define LARGE_WAREHOUSE_9 L"┗━━━━━┛ •  • ┗━━━━━┛"

#define STAIRS_ROOM_UP_0 L"┏━━━━━━━━━━━━━━━━━━┓"
#define STAIRS_ROOM_UP_1 L"┃ ┏━━━━┳━┳━┳━┳━━━┓ ┃"
#define STAIRS_ROOM_UP_2 L"┃ ┃    ┃ ┃ ┃ ┃   ┃ ┃"
#define STAIRS_ROOM_UP_3 L"┗━┛    ┗━┻━┻━╋━━━┫ ┃"
#define STAIRS_ROOM_UP_4 L"•            ┣━━━┫ ┃"
#define STAIRS_ROOM_UP_5 L"•            ┣━━━┫ ┃"
#define STAIRS_ROOM_UP_6 L"┏━┓          ┣━━━┫ ┃"
#define STAIRS_ROOM_UP_7 L"┃ ┃          ┃   ┃ ┃"
#define STAIRS_ROOM_UP_8 L"┃ ┗━━━━━━━━━━┻━━━┛ ┃"
#define STAIRS_ROOM_UP_9 L"┗━━━━━━━━━━━━━━━━━━┛"

#define STAIRS_ROOM_UP_2_0 L"┏━━━━━━━━━━━━━━━━━━┓"
#define STAIRS_ROOM_UP_2_1 L"┃ ┏━━━━┳━┳━┳━┳━━━┓ ┃"
#define STAIRS_ROOM_UP_2_2 L"┃ ┃    ┃ ┃ ┃ ┃   ┃ ┃"
#define STAIRS_ROOM_UP_2_3 L"┃ ┃    ┗━┻━┻━┻━━━┻━┛"
#define STAIRS_ROOM_UP_2_4 L"┃ ┃                •"
#define STAIRS_ROOM_UP_2_5 L"┃ ┃                •"
#define STAIRS_ROOM_UP_2_6 L"┃ ┃              ┏━┓"
#define STAIRS_ROOM_UP_2_7 L"┃ ┃              ┃ ┃"
#define STAIRS_ROOM_UP_2_8 L"┃ ┗━━━━━━━━━━━━━━┛ ┃"
#define STAIRS_ROOM_UP_2_9 L"┗━━━━━━━━━━━━━━━━━━┛"

#define MECHANICAL_ROOM_0 L"┏━━━━━━━━━━━━━━━━━━┓"
#define MECHANICAL_ROOM_1 L"┃ ┏━━━━━━━━━━━━━━┓ ┃"
#define MECHANICAL_ROOM_2 L"┃ ┃┏━━━━━┓       ┃ ┃"
#define MECHANICAL_ROOM_3 L"┃ ┃┃⎔ ⎔ ⎔┃       ┗━┛"
#define MECHANICAL_ROOM_4 L"┃ ┃┗┓┏━━━┛         •"
#define MECHANICAL_ROOM_5 L"┃ ┃┏┛┗━━━┓         •"
#define MECHANICAL_ROOM_6 L"┃ ┃┃⎔ ⎔ ⎔┃       ┏━┓"
#define MECHANICAL_ROOM_7 L"┃ ┃┗━━━━━┛       ┃ ┃"
#define MECHANICAL_ROOM_8 L"┃ ┗━━━┓      ┏━━━┛ ┃"
#define MECHANICAL_ROOM_9 L"┗━━━━━┛ •  • ┗━━━━━┛"

#define HALL_0 L"┏━━━━━┓ •  • ┏━━━━━┓"
#define HALL_1 L"┃ ┏━━━┛      ┗━━━┓ ┃"
#define HALL_2 L"┃ ┃              ┃ ┃"
#define HALL_3 L"┗━┛              ┗━┛"
#define HALL_4 L"•                  •"
#define HALL_5 L"•                  •"
#define HALL_6 L"┏━┓              ┏━┓"
#define HALL_7 L"┃ ┃              ┃ ┃"
#define HALL_8 L"┃ ┗━━━━━━━━━━━━━━┛ ┃"
#define HALL_9 L"┗━━━━━━━━━━━━━━━━━━┛"

#define KEY_ROOM_0 L"┏━━━━━┓ •  • ┏━━━━━┓"
#define KEY_ROOM_1 L"┃ ┏━━━┛      ┗━━━┓ ┃"
#define KEY_ROOM_2 L"┃ ┃ ┏━━┓         ┃ ┃"
#define KEY_ROOM_3 L"┃ ┃ ┗━━┛         ┃ ┃"
#define KEY_ROOM_4 L"┃ ┃              ┃ ┃"
#define KEY_ROOM_5 L"┃ ┃ ┏━━━━━━━━━━┓ ┃ ┃"
#define KEY_ROOM_6 L"┃ ┃ ┃   ┏━━┓   ┃ ┃ ┃"
#define KEY_ROOM_7 L"┃ ┃ ┗━━━┛  ┗━━━┛ ┃ ┃"
#define KEY_ROOM_8 L"┃ ┗━━━━━━━━━━━━━━┛ ┃"
#define KEY_ROOM_9 L"┗━━━━━━━━━━━━━━━━━━┛"

#define RECEPTION_0 L"┏━━━━━━━┓ •  • ┏━━━┓"
#define RECEPTION_1 L"┃ ┏━━━━━┛      ┗━┓ ┃"
#define RECEPTION_2 L"┃ ┃      ┏━━━┓   ┃ ┃"
#define RECEPTION_3 L"┗━┛      ┃   ┃   ┃ ┃"
#define RECEPTION_4 L"•        ┃   ┃   ┃ ┃"
#define RECEPTION_5 L"•        ┃   ┃   ┃ ┃"
#define RECEPTION_6 L"┏━┓      ┗━━━┛   ┃ ┃"
#define RECEPTION_7 L"┃ ┃              ┃ ┃"
#define RECEPTION_8 L"┃ ┗━━━━━┓      ┏━┛ ┃"
#define RECEPTION_9 L"┗━━━━━━━┛ •  • ┗━━━┛"

#define WASHROOM_0 L"┏━━━━━━━━━━━━━━━━━━┓"
#define WASHROOM_1 L"┃ ┏━━━━━━━━━━━━━━┓ ┃"
#define WASHROOM_2 L"┃ ┃Ѻ  Ѻ  Ѻ  Ѻ  Ѻ ┃ ┃"
#define WASHROOM_3 L"┃ ┣━━━━━━━━━━━━━━┻━┛"
#define WASHROOM_4 L"┃ ┃                •"
#define WASHROOM_5 L"┃ ┃                •"
#define WASHROOM_6 L"┃ ┃  ┏━━━┳━━━┳━━━┳━┓"
#define WASHROOM_7 L"┃ ┃  ┃   ┃   ┃   ┃ ┃"
#define WASHROOM_8 L"┃ ┗━━┻━━━┻━━━┻━━━┛ ┃"
#define WASHROOM_9 L"┗━━━━━━━━━━━━━━━━━━┛"

#define TECHNICAL_LAB_1_0 L"┏━━━━━━━━━━━━━━━━━━┓"
#define TECHNICAL_LAB_1_1 L"┃ ┏━━━━━━━━━━━━━━┓ ┃"
#define TECHNICAL_LAB_1_2 L"┃ ┃┏━━━━━━┓┏━━━┓ ┃ ┃"
#define TECHNICAL_LAB_1_3 L"┗━┛┗━━━━━━┛┗━━━┛ ┗━┛"
#define TECHNICAL_LAB_1_4 L"•                  •"
#define TECHNICAL_LAB_1_5 L"•                  •"
#define TECHNICAL_LAB_1_6 L"┏━┓┏━━━┓ ┏━━━┓   ┏━┓"
#define TECHNICAL_LAB_1_7 L"┃ ┃┗━━━┛ ┗━━━┛   ┃ ┃"
#define TECHNICAL_LAB_1_8 L"┃ ┗━━━━━━━━━━━━━━┛ ┃"
#define TECHNICAL_LAB_1_9 L"┗━━━━━━━━━━━━━━━━━━┛"

#define TECHNICAL_LAB_2_0 L"┏━━━━━━━━━━━━━━━━━━┓"
#define TECHNICAL_LAB_2_1 L"┃ ┏━━━━━━━━━━━━━━┓ ┃"
#define TECHNICAL_LAB_2_2 L"┃ ┃  ┏━━━━━━━━━┓ ┃ ┃"
#define TECHNICAL_LAB_2_3 L"┗━┛  ┗━━━━━━━━━┛ ┃ ┃"
#define TECHNICAL_LAB_2_4 L"•                ┃ ┃"
#define TECHNICAL_LAB_2_5 L"•                ┃ ┃"
#define TECHNICAL_LAB_2_6 L"┏━┓ ┏━━━┓   ┏━━┓ ┃ ┃"
#define TECHNICAL_LAB_2_7 L"┃ ┃ ┗━━━┛   ┗━━┛ ┃ ┃"
#define TECHNICAL_LAB_2_8 L"┃ ┗━━━━━━━━━━━━━━┛ ┃"
#define TECHNICAL_LAB_2_9 L"┗━━━━━━━━━━━━━━━━━━┛"

#define LARGE_LAB_0 L"┏━━━━━━ •  • ━━━━━━┓"
#define LARGE_LAB_1 L"┃             ┏━━┓ ┃"
#define LARGE_LAB_2 L"┃ ┏━━┓        ┗━━┛ ┃"
#define LARGE_LAB_3 L"  ┗━━┛              "
#define LARGE_LAB_4 L"•     ┏━━┓         •"
#define LARGE_LAB_5 L"•     ┗━━┛         •"
#define LARGE_LAB_6 L"              ┏━━┓  "
#define LARGE_LAB_7 L"┃ ┏━━┓        ┗━━┛ ┃"
#define LARGE_LAB_8 L"┃ ┗━━┛             ┃"
#define LARGE_LAB_9 L"┗━━━━━━ •  • ━━━━━━┛"

#define TRANS_LAB_0 L"┏━━━━━━━━━━━━━━━━━━┓"
#define TRANS_LAB_1 L"┃ ┏━━━━━━━━━━━━━━┓ ┃"
#define TRANS_LAB_2 L"┃ ┃  ┏━━━━━━━┓   ┃ ┃"
#define TRANS_LAB_3 L"┗━┛  ┗━━━━━━━┛   ┃ ┃"
#define TRANS_LAB_4 L"•                ┃ ┃"
#define TRANS_LAB_5 L"•                ┃ ┃"
#define TRANS_LAB_6 L"┏━┓ ┏━━━━┓  ┏━━┓ ┃ ┃"
#define TRANS_LAB_7 L"┃ ┃ ┗━━━━┛  ┗━━┛ ┃ ┃"
#define TRANS_LAB_8 L"┃ ┗━━━━━━━━━━━━━━┛ ┃"
#define TRANS_LAB_9 L"┗━━━━━━━━━━━━━━━━━━┛"

#define POWER_LAB_0 L"┏━━━━━━━━━━━━━━━━━━┓"
#define POWER_LAB_1 L"┃ ┏━━━━━━━━━━━━━━┓ ┃"
#define POWER_LAB_2 L"┃ ┃              ┃ ┃"
#define POWER_LAB_3 L"┃ ┃    ┏━━━┓     ┗━┛"
#define POWER_LAB_4 L"┃ ┃    ┃ ۞ ┃       •"
#define POWER_LAB_5 L"┃ ┃    ┗━━━┛       •"
#define POWER_LAB_6 L"┃ ┃              ┏━┓"
#define POWER_LAB_7 L"┃ ┃              ┃ ┃"
#define POWER_LAB_8 L"┃ ┗━━━━━━━━━━━━━━┛ ┃"
#define POWER_LAB_9 L"┗━━━━━━━━━━━━━━━━━━┛"

#define POWER_INFO_0 L"┏━━━━━━━━━━━━━━━━━━┓"
#define POWER_INFO_1 L"┃ ┏━━━━━━━━━━━━━━┓ ┃"
#define POWER_INFO_2 L"┃ ┃ ┏━┓  ┏━━┓    ┃ ┃"
#define POWER_INFO_3 L"┃ ┃ ┃ ┃  ┗━━┛    ┗━┛"
#define POWER_INFO_4 L"┃ ┃ ┃ ┃            •"
#define POWER_INFO_5 L"┃ ┃ ┃ ┃            •"
#define POWER_INFO_6 L"┃ ┃ ┃ ┃    ┏━━┓  ┏━┓"
#define POWER_INFO_7 L"┃ ┃ ┗━┛    ┗━━┛  ┃ ┃"
#define POWER_INFO_8 L"┃ ┗━━━━━━━━━━━━━━┛ ┃"
#define POWER_INFO_9 L"┗━━━━━━━━━━━━━━━━━━┛"

#define TRANS_ROOM_0 L"┏━━━━━┓ •  • ┏━━━━━┓"
#define TRANS_ROOM_1 L"┃ ┏━━━┛      ┗━━━┓ ┃"
#define TRANS_ROOM_2 L"┃ ┃  ┏ ━┻━━┻━ ┓  ┃ ┃"
#define TRANS_ROOM_3 L"┗━┛  ┃ ┏ ━━ ┓ ┃  ┗━┛"
#define TRANS_ROOM_4 L"•    ┃ ┃ ┏┓ ┃ ┃    •"
#define TRANS_ROOM_5 L"•    ┃ ┃ ┗┛ ┃ ┃    •"
#define TRANS_ROOM_6 L"┏━┓  ┃ ┗ ━━ ┛ ┃  ┏━┓"
#define TRANS_ROOM_7 L"┃ ┃  ┗ ━┳━━┳━ ┛  ┃ ┃"
#define TRANS_ROOM_8 L"┃ ┗━━━┓      ┏━━━┛ ┃"
#define TRANS_ROOM_9 L"┗━━━━━┛ •  • ┗━━━━━┛"

#define T_CORE_ROOM_0 L"┏━━━━━━━━━━━━━━━━━━┓"
#define T_CORE_ROOM_1 L"┃ ┏━━━━━━━━━━━━━━┓ ┃"
#define T_CORE_ROOM_2 L"┃ ┃              ┃ ┃"
#define T_CORE_ROOM_3 L"┃ ┃    ┏━━━━┓    ┃ ┃"
#define T_CORE_ROOM_4 L"┃ ┃    ┃ ۞  ┃    ┃ ┃"
#define T_CORE_ROOM_5 L"┃ ┃    ┗━━━━┛    ┃ ┃"
#define T_CORE_ROOM_6 L"┃ ┃              ┃ ┃"
#define T_CORE_ROOM_7 L"┃ ┃              ┃ ┃"
#define T_CORE_ROOM_8 L"┃ ┗━━━┓      ┏━━━┛ ┃"
#define T_CORE_ROOM_9 L"┗━━━━━┛ •  • ┗━━━━━┛"

#define FUSE_ROOM_0 L"┏━━━━━━━━━━━━━━━━━━┓"
#define FUSE_ROOM_1 L"┃ ┏━━━━━━━━━━━━━━┓ ┃"
#define FUSE_ROOM_2 L"┃ ┃ ┏━━━━━━━━━━┓ ┃ ┃"
#define FUSE_ROOM_3 L"┗━┛ ┗━━━━━━━━━━┛ ┃ ┃"
#define FUSE_ROOM_4 L"•                ┃ ┃"
#define FUSE_ROOM_5 L"•                ┃ ┃"
#define FUSE_ROOM_6 L"┏━┓ ┏━━━━━━━━━━┓ ┃ ┃"
#define FUSE_ROOM_7 L"┃ ┃ ┗━━━━━━━━━━┛ ┃ ┃"
#define FUSE_ROOM_8 L"┃ ┗━━━━━━━━━━━━━━┛ ┃"
#define FUSE_ROOM_9 L"┗━━━━━━━━━━━━━━━━━━┛"

#define GEAR_ROOM_0 L"┏━━━━━━━━━━━━━━━━━━┓"
#define GEAR_ROOM_1 L"┃ ┏━━━━━━━━━━━━━━┓ ┃"
#define GEAR_ROOM_2 L"┃ ┃ ┏━┓   ┏━━━━┓ ┃ ┃"
#define GEAR_ROOM_3 L"┗━┛ ┗━┛   ┃    ┃ ┃ ┃"
#define GEAR_ROOM_4 L"•         ┃    ┃ ┃ ┃"
#define GEAR_ROOM_5 L"•         ┃    ┃ ┃ ┃"
#define GEAR_ROOM_6 L"┏━┓  ┏━━━┓┃    ┃ ┃ ┃"
#define GEAR_ROOM_7 L"┃ ┃  ┗━━━┛┗━━━━┛ ┃ ┃"
#define GEAR_ROOM_8 L"┃ ┗━━━━━━━━━━━━━━┛ ┃"
#define GEAR_ROOM_9 L"┗━━━━━━━━━━━━━━━━━━┛"

#define NOT_ILLUMINATED_0 L"████████████████████"
#define NOT_ILLUMINATED_1 L"████████████████████"
#define NOT_ILLUMINATED_2 L"████████████████████"
#define NOT_ILLUMINATED_3 L"████████████████████"
#define NOT_ILLUMINATED_4 L"████████████████████"
#define NOT_ILLUMINATED_5 L"████████████████████"
#define NOT_ILLUMINATED_6 L"████████████████████"
#define NOT_ILLUMINATED_7 L"████████████████████"
#define NOT_ILLUMINATED_8 L"████████████████████"
#define NOT_ILLUMINATED_9 L"████████████████████"

#define ERROR_ROOM_0 L"┏━━━━━━━━━━━━━━━━━━┓"
#define ERROR_ROOM_1 L"┃                  ┃"
#define ERROR_ROOM_2 L"┃                  ┃"
#define ERROR_ROOM_3 L"┃   There was an   ┃"
#define ERROR_ROOM_4 L"┃   error loading  ┃"
#define ERROR_ROOM_5 L"┃   this graphic   ┃"
#define ERROR_ROOM_6 L"┃   description    ┃"
#define ERROR_ROOM_7 L"┃                  ┃"
#define ERROR_ROOM_8 L"┃                  ┃"
#define ERROR_ROOM_9 L"┗━━━━━━━━━━━━━━━━━━┛"

#endif